import React, { useState } from 'react'
import { useIsClient } from 'usehooks-ts';
import { useCart } from 'react-use-cart'
import toast, { Toaster } from 'react-hot-toast';
import Head from 'next/head';

const notify = () => toast('Zakaz berish uchun Login qil');

const Cart = () => {
    const {items,isEmpty,updateItemQuantity,removeItem,emptyCart,cartTotal} = useCart()
        const [name,setName] = useState('')
        const [size,setSize] = useState('')
        const [sms,setSms] = useState('Majburiy emas')
        const isClient = useIsClient()
        
    
        const postTest = () => {
          axios.post(
            `https://api.telegram.org/bot5378253930:AAEW0rlP7j7KA50TxsypNSLLKvQ5jYnNPfc/sendMessage?chat_id=-1001553163227&text=${encodeURIComponent(
              `<b>Details:</b>
              Ism: ${name}
              Razmer: ${size}
              SMS: ${sms}
      
          
      ${items
        .map((item) => {
          return `
      <b>${item.name}</b>
      ${item.quantity} x ${item.price} $
          `;
        })
        .join("")}        
      <b>Total:</b> ${cartTotal} $`
            )}&parse_mode=html`
          )
          .then(() =>  {
            emptyCart()
            window.location.reload()
          })
        };


  return (
    <>
      <Head>
        <title>Sammi | Cart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.sammi.ac/logo.svg" />
      </Head>
   {isClient &&    <div className="container">
{isEmpty ? (
    <div className="empty">
<img src="https://cdn-icons-png.flaticon.com/512/4859/4859591.png" alt="" />
    </div>
):(    <div className="korzina">
 <div className="dd">
    <button onClick={() => emptyCart()}>Tozalash🗑️</button>
    </div>   
    <br />
    <br />
    <div className="main">
    {items.map((el) => {
        const priceCount = el.price * el.quantity;
       return(
           <div className="item" key={el.id}>
           <img src={el.rasm} alt="" />
           <h3>{el.name}</h3>
           <b>{priceCount}so'm</b>
           <br />
           <div className="gg">
           <button onClick={() => updateItemQuantity(el.id, el.quantity -1)}>-</button>
           <b>{el.quantity}</b>
           <button onClick={() => updateItemQuantity(el.id, el.quantity +1)}>+</button>
           </div>
           <h2 onClick={() => removeItem(el.id)}>🗑️</h2>
       </div>
       );
    })}
  </div>
    <div className='der'><h1>Total: {cartTotal} So'm</h1></div>
  {localStorage.getItem('parol') ? (
    <>
  <div className="offer">
    <input value={name} onChange={(e) => setName(e.target.value)} type="text" placeholder='Ism'/>
    <input disabled={!name} value={size} onChange={(e) => setSize(e.target.value)}  type="text" placeholder='Email'/>
    <textarea  value={sms} onChange={(e) => setSms(e.target.value)} placeholder='SMS'></textarea>
    <button disabled={!size} onClick={() => postTest()}>Zakaz berish</button>

    </div>
    </>
  ):(
    <>
    <div className="ff"> <button onClick={notify}>Login👤</button></div>
   
    <Toaster />
    </>
    
  )}
  
   </div>)}
</div> }
<br />
<br />
    </>
  )
}

export default Cart
