import { courses } from "@/courses";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sammi proect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.sammi.ac/logo.svg" />
      </Head>
    
      <div className="container">
        <br/>
        <br/>
        <br/>
        <br/> 
     
      <div className="ura">
        
          <div className="title">
          <div className="f"><p>Kurslar </p><h2>/</h2> <h1>Loyihalar</h1></div>
          <span><input type="text" placeholder="Qidirish" />
          <h3>select</h3></span>
        </div>
        <div className="wrapper">
          {courses?.map((el) => {
            return(
              <Link href={`/course/${el?.id}`} className="card" >
                <div className="btns">
                  <button>{el?.soha}</button>
                  <button>{el?.level}</button>

                </div>
                <img src={el?.rasm} alt="" />
                <h3>{el?.name}</h3>
              </Link>
            )
          })}
        </div>
        </div>
      </div>
    
    </>
  );
}
