import { courses } from "@/courses";
import Head from "next/head";
// import { Image } from "antd";
import { useRouter } from "next/router";
import React from "react";
import { useCart } from 'react-use-cart';
import { useIsClient } from 'usehooks-ts';

const SinglePage = () => {
  const router = useRouter();
  const isClient = useIsClient()
  const {getItem,addItem,removeItem} = useCart()
  const findSingle = courses?.find((el) => {
    return el?.id == router.query.id;
  });

  return (
    <>
      <Head>
        <title>Sammi | {findSingle?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.sammi.ac/logo.svg" />
      </Head>
      <div className="container">
        <section>
          <div className="left-image">
            <img className="img" src={findSingle?.rasm} />
          </div>
         {isClient && (
           <div className="right-contents">
           <h1>{findSingle?.name}</h1>
           <h2>Soha: {findSingle?.soha}</h2>
           <b>{findSingle?.price.toLocaleString()}so'm</b>
           <p>Level: {findSingle?.level}</p>
          {!getItem(findSingle?.id) ? (
            <button onClick={() => addItem(findSingle)} className="add">Sotib Olish</button>
          ):(  
            <button onClick={() => removeItem(findSingle?.id)} className="remove">Bekor Qilish</button>
           )}
        
         </div>
         )}
        </section>
        <div className="back">
          <button onClick={() => router.back()}>Back to Courses</button>
        </div>
      </div>
    </>
  );
};

export default SinglePage;
